#───────────────────────────────────────────────────────────────
# CareerPilot Morning Scan — Auto-generated wrapper
# Runs unattended via Windows Task Scheduler
# Do not edit — regenerated by Register-MorningScan.ps1
#───────────────────────────────────────────────────────────────

$ErrorActionPreference = 'Continue'
$date     = Get-Date -Format 'yyyy-MM-dd'
$time     = Get-Date -Format 'HHmm'
$logFile  = Join-Path 'F:\Projects\CareerPilot\scanner\data\logs' "scan_${date}_${time}.log"

# Start logging
Start-Transcript -Path $logFile -Force | Out-Null

Write-Host "CareerPilot Morning Scan"
Write-Host "Date: $date  Time: $time"
Write-Host "========================================="

# ── Load encrypted API key ──
$keyFile = 'F:\Projects\CareerPilot\scanner\data\.api_key.enc'
if (-not (Test-Path $keyFile)) {
    Write-Error "API key file not found: $keyFile"
    Write-Error "Run Start-CareerPageScan.ps1 interactively to save your key."
    Stop-Transcript | Out-Null
    exit 1
}

try {
    $encrypted = (Get-Content $keyFile -Raw).Trim()
    $secure    = $encrypted | ConvertTo-SecureString
    $bstr      = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    $apiKey    = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)

    if (-not $apiKey -or -not $apiKey.StartsWith("sk-ant-")) {
        Write-Error "Decrypted API key appears invalid."
        Stop-Transcript | Out-Null
        exit 1
    }

    $env:ANTHROPIC_API_KEY = $apiKey
    $apiKey = $null
    [System.GC]::Collect()
    Write-Host "[key] API key loaded from encrypted store"
}
catch {
    Write-Error "Failed to decrypt API key: $_"
    Write-Error "The key was encrypted by a specific user account. Ensure this task runs as that user."
    Stop-Transcript | Out-Null
    exit 1
}

# ── Run the scan ──
$reportPath = Join-Path 'F:\Projects\CareerPilot\scanner\data\reports' "morning_$date"

Write-Host "
Running scan..."
& python "F:\Projects\CareerPilot\scanner\morning_scan.py" --output $reportPath

Write-Host "
Exporting JSON for dashboard..."
& python "F:\Projects\CareerPilot\scanner\morning_scan.py" --json --output (Join-Path 'F:\Projects\CareerPilot\scanner\data\reports' "latest.json")

# ── Cleanup ──
$env:ANTHROPIC_API_KEY = $null

Write-Host "
========================================="
Write-Host "Scan complete."
Write-Host "Report: $reportPath.txt"
Write-Host "Log:    $logFile"

Stop-Transcript | Out-Null

# ── Prune old logs (keep 14 days) ──
Get-ChildItem 'F:\Projects\CareerPilot\scanner\data\logs' -Filter "scan_*.log" |
    Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-14) } |
    Remove-Item -Force -ErrorAction SilentlyContinue
