<#
.SYNOPSIS
    Register-MorningScan.ps1 — Set up CareerPilot morning scan as a Windows Scheduled Task

.DESCRIPTION
    Creates a scheduled task that runs the morning scan daily at 7:00 AM.
    The wrapper loads the encrypted API key from data\.api_key.enc (Windows DPAPI),
    runs the scan, saves a date-stamped report + latest.json, and logs everything.

.EXAMPLE
    .\Register-MorningScan.ps1                  # Register daily at 7:00 AM
    .\Register-MorningScan.ps1 -Time "06:30"    # Register at 6:30 AM
    .\Register-MorningScan.ps1 -Quick           # Direct employers only (faster)
    .\Register-MorningScan.ps1 -Unregister      # Remove the scheduled task
#>

param(
    [string]$Time = "07:00",
    [string]$PythonPath = "python",
    [string]$ProjectRoot = $PSScriptRoot,
    [switch]$Quick,
    [switch]$Unregister
)

$TaskName = "CareerPilot-MorningScan"
$Description = "CareerPilot morning job scan — Indeed, Dice, and direct employer career pages"

if ($Unregister) {
    Write-Host "`n  Removing scheduled task '$TaskName'..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "  Done.`n" -ForegroundColor Green
    return
}

# ── Validate paths ──

$ScanScript = Join-Path $ProjectRoot "morning_scan.py"
$KeyFile    = Join-Path $ProjectRoot "data" ".api_key.enc"
$ReportDir  = Join-Path $ProjectRoot "data" "reports"
$LogDir     = Join-Path $ProjectRoot "data" "logs"

if (-not (Test-Path $ScanScript)) {
    Write-Error "morning_scan.py not found at $ScanScript"
    return
}

if (-not (Test-Path $KeyFile)) {
    Write-Error @"
Encrypted API key not found at $KeyFile.
Run Start-CareerPageScan.ps1 first to enter and save your API key,
or run:  .\Start-CareerPageScan.ps1 -SaveKey
"@
    return
}

# Ensure directories exist
foreach ($dir in @($ReportDir, $LogDir)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

$QuickFlag = if ($Quick) { " --quick" } else { "" }

# ── Generate the wrapper script ──
# This runs unattended: loads the encrypted key, runs the scan, logs output.

$WrapperScript = Join-Path $ProjectRoot "data" "run_morning_scan.ps1"
$WrapperContent = @"
#───────────────────────────────────────────────────────────────
# CareerPilot Morning Scan — Auto-generated wrapper
# Runs unattended via Windows Task Scheduler
# Do not edit — regenerated by Register-MorningScan.ps1
#───────────────────────────────────────────────────────────────

`$ErrorActionPreference = 'Continue'
`$date     = Get-Date -Format 'yyyy-MM-dd'
`$time     = Get-Date -Format 'HHmm'
`$logFile  = Join-Path '$LogDir' "scan_`${date}_`${time}.log"

# Start logging
Start-Transcript -Path `$logFile -Force | Out-Null

Write-Host "CareerPilot Morning Scan"
Write-Host "Date: `$date  Time: `$time"
Write-Host "========================================="

# ── Load encrypted API key ──
`$keyFile = '$KeyFile'
if (-not (Test-Path `$keyFile)) {
    Write-Error "API key file not found: `$keyFile"
    Write-Error "Run Start-CareerPageScan.ps1 interactively to save your key."
    Stop-Transcript | Out-Null
    exit 1
}

try {
    `$encrypted = Get-Content `$keyFile -Raw
    `$secure    = `$encrypted | ConvertTo-SecureString
    `$bstr      = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR(`$secure)
    `$apiKey    = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(`$bstr)
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR(`$bstr)

    if (-not `$apiKey -or -not `$apiKey.StartsWith("sk-ant-")) {
        Write-Error "Decrypted API key appears invalid."
        Stop-Transcript | Out-Null
        exit 1
    }

    `$env:ANTHROPIC_API_KEY = `$apiKey
    `$apiKey = `$null
    [System.GC]::Collect()
    Write-Host "[key] API key loaded from encrypted store"
}
catch {
    Write-Error "Failed to decrypt API key: `$_"
    Write-Error "The key was encrypted by a specific user account. Ensure this task runs as that user."
    Stop-Transcript | Out-Null
    exit 1
}

# ── Run the scan ──
`$reportPath = Join-Path '$ReportDir' "morning_`$date"

Write-Host "`nRunning scan..."
& $PythonPath "$ScanScript"$QuickFlag --output `$reportPath

Write-Host "`nExporting JSON for dashboard..."
& $PythonPath "$ScanScript"$QuickFlag --json --output (Join-Path '$ReportDir' "latest.json")

# ── Cleanup ──
`$env:ANTHROPIC_API_KEY = `$null

Write-Host "`n========================================="
Write-Host "Scan complete."
Write-Host "Report: `$reportPath.txt"
Write-Host "Log:    `$logFile"

Stop-Transcript | Out-Null

# ── Prune old logs (keep 14 days) ──
Get-ChildItem '$LogDir' -Filter "scan_*.log" |
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-14) } |
    Remove-Item -Force -ErrorAction SilentlyContinue
"@

$WrapperContent | Set-Content -Path $WrapperScript -Encoding UTF8

# ── Register the scheduled task ──

$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$WrapperScript`"" `
    -WorkingDirectory $ProjectRoot

$Trigger = New-ScheduledTaskTrigger -Daily -At $Time

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30)

# Remove existing task if present
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Description $Description `
    -RunLevel Limited

Write-Host ""
Write-Host "  ══════════════════════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host "  Scheduled task registered successfully" -ForegroundColor Green
Write-Host "  ══════════════════════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Task name:   $TaskName" -ForegroundColor White
Write-Host "  Schedule:    Daily at $Time" -ForegroundColor Cyan
Write-Host "  Reports:     $ReportDir" -ForegroundColor Cyan
Write-Host "  Logs:        $LogDir" -ForegroundColor Cyan
Write-Host "  API key:     Loaded from encrypted store (DPAPI)" -ForegroundColor Cyan
if ($Quick) {
    Write-Host "  Mode:        Quick (direct employers only)" -ForegroundColor Yellow
} else {
    Write-Host "  Mode:        Full (Direct + Indeed + Dice)" -ForegroundColor Cyan
}
Write-Host ""
Write-Host "  Commands:" -ForegroundColor DarkGray
Write-Host "    Run now:     Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "    Check log:   Get-Content (Get-ChildItem '$LogDir' -Filter 'scan_*.log' | Sort-Object -Descending | Select-Object -First 1)"
Write-Host "    Unregister:  .\Register-MorningScan.ps1 -Unregister"
Write-Host ""
